name: Deploy .NET App to IIS Server

on:
  push:
    branches:
      - main    # whenever you push to main branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # or 7.0.x, depending on your project version

    - name: Publish Project
      run: dotnet publish SampleCoreWebAPI.csproj --configuration Release --output ./publish

    - name: Check msdeploy exists
      run: |
        where msdeploy || echo "msdeploy not found"

    - name: IIS Deploy
      uses: ChristopheLav/iis-deploy@v1.0.0
      with:
        website-name: 'githubWorkFlow'   # Your IIS site name
        msdeploy-service-url: 'https://192.168.1.84:8172/msdeploy.axd'
        msdeploy-username: 'administrator'
        msdeploy-password: ${{ secrets.MSDEPLOY_PASSWORD }}
        source-path: './publish'
